services:
  caddy:
    image: caddy:2-alpine
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
      - target: 2019
        published: 2019
        mode: host
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - estacao-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  estacao-network:
    external: true

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
