networks:
  estacaoterapia_backend:
    external: true
    name: estacaoterapia_backend

services:
  postgres:
    image: postgres:16-alpine
    secrets:
      - source: postgres_env
        target: /run/secrets/postgres_env
        mode: 0444
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      estacaoterapia_backend:
        aliases:
          - postgres
          - postgres.estacaoterapia_backend
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "PGPASSWORD=$$(grep POSTGRES_PASSWORD /run/secrets/postgres_env | cut -d= -f2) psql -U $$(grep POSTGRES_USER /run/secrets/postgres_env | cut -d= -f2) -d $$(grep POSTGRES_DB /run/secrets/postgres_env | cut -d= -f2) -c 'SELECT 1;' >/dev/null 2>&1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
        monitor: 60s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s

volumes:
  postgres_data:
    external: true

secrets:
  postgres_env:
    external: true
