networks:
  estacaoterapia_backend:
    external: true
    name: estacaoterapia_backend

services:
  api:
    image: estacaoterapia-api:${TAG}
    command: ['node', 'dist/server.js']

    # ❗ NÃO sobrescreve ENTRYPOINT
    # ENTRYPOINT vem do Dockerfile (/entrypoint.sh)

    secrets:
      - source: estacao_api_env
        target: /run/secrets/estacao_api.env
        mode: 0444
      - source: redis_password
        target: /run/secrets/redis_password
        mode: 0444

    environment:
      NODE_ENV: production
      PORT: '3333'
      NODE_OPTIONS: '--max-old-space-size=2048'

      # PostgreSQL / PgBouncer
      PG_HOST: pgbouncer
      PG_PORT: '6432'
      PG_HOST_DIRECT: postgres
      PG_PORT_DIRECT: '5432'
      POSTGRES_DB: estacaoterapia

      # Redis (senha vem EXCLUSIVAMENTE do secret)
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      REDIS_DB: '1'

      # Backups
      BACKUP_DIR: /app/backups

    volumes:
      - documentos_data:/app/documentos
      - backups_data:/app/backups

    deploy:
      replicas: 2 # Para zero downtime, use pelo menos 2 réplicas
      placement:
        constraints:
          - node.role == manager
      update_config:
        order: start-first # Garante que a nova instância suba antes de remover a antiga
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
      restart_policy:
        condition: any
        delay: 10s
        window: 120s

    networks:
      estacaoterapia_backend:
        aliases:
          - api
          - estacaoterapia_api

volumes:
  documentos_data:
    external: true
  backups_data:
    external: true

secrets:
  estacao_api_env:
    external: true
  redis_password:
    external: true
