# ============================================
# API BACKEND - DOCKER SWARM STACK
# Para uso com Docker Swarm
# Use docker-compose.yml na raiz para Docker Compose
# ============================================

networks:
  estacao-backend-network:
    external: true
    name: estacao-backend-network
  
  estacao-network:
    external: false
    driver: overlay

services:
  # =====================================
  # POSTGRESQL
  # =====================================
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: estacaoterapia
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - estacao-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U estacaoterapia -d estacaoterapia"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"
      - "-c"
      - "max_parallel_maintenance_workers=2"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # =====================================
  # REDIS
  # =====================================
  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --requirepass
      - "$$(cat /run/secrets/redis_password)"
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --maxmemory
      - 512mb
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - "900 1"
      - --save
      - "300 10"
      - --save
      - "60 10000"
      - --tcp-backlog
      - "511"
      - --timeout
      - "300"
      - --tcp-keepalive
      - "300"
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    networks:
      - estacao-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # =====================================
  # API NODE.JS – PRODUÇÃO
  # =====================================
  api:
    image: estacaoterapia-api:prd-{{TAG}}
    user: '997:1001'

    entrypoint: ['/bin/sh', '/entrypoint.sh']
    command: ['node', 'dist/server.js']

    secrets:
      - source: estacao_api_env
        target: estacao_api.env

    environment:
      NODE_ENV: production
      NODE_OPTIONS: '--max-old-space-size=2048'
      PG_HOST: pgbouncer
      PG_PORT: '6432'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      REDIS_DB: '1'
      # REDIS_PASSWORD e REDIS_URL devem vir dos secrets (estacao_api_env)
      # Não definir aqui para evitar exposição

    volumes:
      - type: bind
        source: ./entrypoint.sh
        target: /entrypoint.sh
        read_only: true
      - type: volume
        source: documentos_data
        target: /app/documentos
      - type: bind
        source: ./backups
        target: /app/backups
        read_only: true

    tmpfs:
      - /tmp
      - /app/data

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3333/health']
      interval: 10s
      timeout: 5s
      retries: 3

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    networks:
      - estacao-backend-network
      - estacao-network

  # =====================================
  # PGBOUNCER
  # =====================================
  pgbouncer:
    image: edoburu/pgbouncer:latest
    secrets:
      - source: pgbouncer.ini
        target: /etc/pgbouncer/pgbouncer.ini
      - source: userlist.txt
        target: /etc/pgbouncer/userlist.txt
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    networks:
      estacao-backend-network:
        aliases:
          - pgbouncer

  # =====================================
  # SOCKET SERVER
  # =====================================
  socket-server:
    image: estacaoterapia-socket-server:prd-{{TAG}}
    user: '997:1001'

    entrypoint: ['/bin/sh', '/entrypoint.sh']
    command: ['node', 'dist/socket/server.js']

    secrets:
      - source: estacao_socket_env
        target: estacao_socket.env

    environment:
      NODE_ENV: production
      PORT: '3334'
      SOCKET_SERVER: 'true'
      SERVER_TYPE: socket
      PG_HOST: pgbouncer
      PG_PORT: '6432'
      API_BASE_URL: 'http://api:3333'
      # Credenciais devem vir dos secrets (estacao_socket_env)

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3334/health']
      interval: 10s
      timeout: 5s
      retries: 3

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 5s
      restart_policy:
        condition: on-failure

    networks:
      - estacao-backend-network
      - estacao-network

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true
  documentos_data:
    external: true

secrets:
  estacao_api_env:
    external: true
  estacao_socket_env:
    external: true
  pgbouncer.ini:
    external: true
  userlist.txt:
    external: true
  postgres_user:
    external: true
  postgres_password:
    external: true
  redis_password:
    external: true